import { exhibitionReviewEnabled } from "../../config/exhibitionReview";
import React, { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { getCurationAccess } from "../../api/publicGalleries";
import { getMyExhibitions, hasSession } from "../../api/exhibitionCommunity";
import * as api from "../../api/exhibitionBusiness";
import { offerKind, priceText } from "./BusinessPublic";
import "./exhibitions.css";
import "./community.css";
import "./business.css";

function useData<T>(load:(signal:AbortSignal)=>Promise<T>,deps:unknown[],enabled=true) {
  const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(enabled),[version,setVersion]=useState(0);
  useEffect(()=>{const controller=new AbortController();setData(null);setError('');setLoading(enabled);if(!enabled)return()=>controller.abort();load(controller.signal).then(value=>{if(!controller.signal.aborted)setData(value);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();
    // Request inputs are explicitly supplied by each caller.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[...deps,enabled,version]);
  return {data,error,loading,reload:()=>setVersion(v=>v+1)};
}
function Feedback({loading,error,reload}:{loading:boolean;error:string;reload:()=>void}){return loading?<p role="status">불러오는 중이에요…</p>:error?<div role="alert" className="exhibition-message"><p>{error}</p><button onClick={reload}>다시 불러오기</button></div>:null;}
function Shell({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <div className="exhibitions-page business-page"><nav className="community-nav" aria-label="제작자 메뉴"><Link to="/">홈</Link>{exhibitionReviewEnabled && <><Link to="/mypage/publications">내 전시 심사</Link></>}<Link to="/mypage/business">통계·상품 연결</Link><Link to="/pricing">요금제·도입 안내</Link><Link to="/workspaces">작업 공간</Link></nav><header className="exhibitions-intro"><span className="exhibitions-eyebrow">DDUKDDAK · BUSINESS</span><h1>{title}</h1><p>{description}</p></header>{children}</div>;}
function Pager({page,total,setPage}:{page:number;total:number;setPage:(n:number)=>void}){return total>1?<nav className="exhibition-pagination" aria-label="관리 목록 페이지"><button disabled={page<=1} onClick={()=>setPage(page-1)}>이전</button><span>{page} / {total}</span><button disabled={page>=total} onClick={()=>setPage(page+1)}>다음</button></nav>:null;}
const labels:{[K in keyof api.Metrics]:string}={views:'상세 방문',entry_start:'관람 입장 요청',product_click:'상품 이동',reservation_click:'예약 이동',coupon_reveal:'쿠폰 확인',promotion_click:'프로모션 유입'};
const reviewLabel=(status:string)=>({pending:'심사 대기',approved:'승인',rejected:'반려'}[status]||status);
function Stats({data}:{data:api.Analytics}) {
  const peak=Math.max(1,...data.daily.map(row=>row.views));
  function csv(){const rows=[['날짜',...Object.values(labels)],...data.daily.map(row=>[row.day,...Object.keys(labels).map(k=>row[k as keyof api.Metrics])])];const text='\uFEFF'+rows.map(row=>row.join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`exhibition-${data.code}-${data.from}-${data.to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <section className="business-stats"><div className="business-toolbar"><p>{data.from} — {data.to} · 한국 날짜 기준</p><button onClick={csv}>일별 통계 CSV 저장</button></div><div className="business-metrics">{Object.entries(labels).map(([key,label])=><article key={key}><span>{label}</span><strong>{data.totals[key as keyof api.Metrics].toLocaleString('ko-KR')}</strong></article>)}</div><p className="business-muted">현재 찜 {data.current.saved.toLocaleString()} · 현재 좋아요 {data.current.liked.toLocaleString()}</p>
    <div className="business-chart" role="img" aria-label={`${data.days}일간 상세 방문 추이. 총 ${data.totals.views}회. 아래 일별 표에서 정확한 수치를 확인할 수 있어요.`}>{data.daily.map(row=><div key={row.day} title={`${row.day}: ${row.views}회`}><span style={{height:`${row.views/peak*100}%`}} /></div>)}</div><div className="business-chart-axis"><span>{data.from}</span><span>{data.to}</span></div>
    <details className="business-table"><summary>일별 수치 보기</summary><div className="business-table-scroll"><table><thead><tr><th>날짜</th>{Object.values(labels).map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{data.daily.map(row=><tr key={row.day}><th>{row.day}</th>{Object.keys(labels).map(k=><td key={k}>{row[k as keyof api.Metrics]}</td>)}</tr>)}</tbody></table></div></details>
    {!!data.offers.length&&<div className="business-table"><h3>연결별 이용</h3><div className="business-table-scroll"><table><thead><tr><th>이름</th><th>종류</th><th>선택 기간 이용</th></tr></thead><tbody>{data.offers.map(offer=><tr key={offer.id}><th>{offer.title}</th><td>{offerKind(offer.kind)}</td><td>{offer.total}</td></tr>)}</tbody></table></div></div>}
    <p className="business-muted">같은 계정 또는 브라우저의 같은 행동은 하루에 한 번 집계해요. 링크별 집계는 각각 계산해요. 상세 방문은 웹 집계 도입 이후 기록이며, 기존 누적 조회수는 포함하지 않아요. 입장 요청은 공간 로딩 시작을 뜻하고, 외부 이동·쿠폰 확인은 실제 구매·예약 완료나 쿠폰 사용을 뜻하지 않아요.</p>
  </section>;
}
const emptyOffer=(code:string):api.Offer=>({id:'',code,kind:'product',title:'',description:'',url:'',couponCode:'',startsOn:null,endsOn:null,enabled:true,sortOrder:0,reviewStatus:'pending',reviewNote:'',revision:1});
function OfferEditor({code,initial,done}:{code:string;initial:api.Offer;done:()=>void}) {
  const [form,setForm]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const field=(name:keyof api.Offer,value:unknown)=>setForm({...form,[name]:value});
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api.saveOffer(code,form);done();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <form className="business-form" onSubmit={save}><h3>{form.id?'연결 수정':'새 연결 만들기'}</h3><p className="business-muted">신규 등록과 수정은 검토 후 노출돼요. 공개를 끄면 저장 후 즉시 숨겨져요.</p><fieldset disabled={busy}><label>종류<select value={form.kind} onChange={e=>field('kind',e.target.value)}><option value="product">상품 구매 연결</option><option value="reservation">외부 예약 연결</option><option value="coupon">공통 쿠폰 코드</option></select></label><label>제목<input required maxLength={100} value={form.title} onChange={e=>field('title',e.target.value)}/></label><label>설명·사용 조건<textarea rows={3} maxLength={500} value={form.description} onChange={e=>field('description',e.target.value)}/></label><label>외부 HTTPS 주소<input required type="url" maxLength={1000} placeholder="https://..." value={form.url} onChange={e=>field('url',e.target.value)}/></label>{form.kind==='coupon'&&<label>쿠폰 코드<input required maxLength={80} value={form.couponCode} onChange={e=>field('couponCode',e.target.value)}/><small>관람객에게 같은 코드를 안내해요. 할인·사용 조건은 외부 사용처에 먼저 설정해 주세요.</small></label>}<div className="business-form-row"><label>시작일 · 선택<input type="date" value={form.startsOn||''} onChange={e=>field('startsOn',e.target.value||null)}/></label><label>종료일 · 선택<input type="date" min={form.startsOn||undefined} value={form.endsOn||''} onChange={e=>field('endsOn',e.target.value||null)}/></label><label>노출 순서<input required type="number" min={0} max={999} value={form.sortOrder} onChange={e=>field('sortOrder',Number(e.target.value))}/></label></div><label className="business-check"><input type="checkbox" checked={form.enabled} onChange={e=>field('enabled',e.target.checked)}/>공개 요청</label><button className="discovery-primary" disabled={busy}>{busy?'저장 중…':'연결 저장'}</button><button type="button" onClick={done}>닫기</button></fieldset>{error&&<p role="alert">{error}</p>}</form>;
}
function CreatorSelected({code}:{code:string}) {
  const [days,setDays]=useState(30),[tab,setTab]=useState('stats'),[editing,setEditing]=useState<api.Offer|null>(null);
  const stats=useData(signal=>api.getAnalytics(code,days,signal),[code,days],tab==='stats');
  const offers=useData(signal=>api.getOffers(code,true,signal),[code],tab==='offers');
  return <><nav className="exhibition-filter-chips" aria-label="제작자 기능"><button aria-pressed={tab==='stats'} onClick={()=>setTab('stats')}>전시 통계</button><button aria-pressed={tab==='offers'} onClick={()=>setTab('offers')}>상품·예약·쿠폰</button></nav>{tab==='stats'?<><label className="business-period">집계 기간 <select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>최근 7일</option><option value={30}>최근 30일</option><option value={90}>최근 90일</option></select></label><Feedback {...stats}/>{stats.data&&<Stats data={stats.data}/>}</>:<><Feedback {...offers}/>{editing?<OfferEditor key={editing.id||'new'} code={code} initial={editing} done={()=>{setEditing(null);offers.reload();}}/>:<button className="discovery-primary" onClick={()=>setEditing(emptyOffer(code))}>새 연결 만들기 +</button>}<div className="business-owned-offers">{offers.data?.offers.map(offer=><article key={offer.id}><span className={`community-status ${offer.reviewStatus}`}>{reviewLabel(offer.reviewStatus)}</span><h3>{offer.title}</h3><p>{offerKind(offer.kind)} · {offer.enabled?'공개 요청 중':'숨김'}</p><p className="business-url">{offer.url}</p>{offer.reviewNote&&<p>운영자 안내: {offer.reviewNote}</p>}<button disabled={!!editing} onClick={()=>setEditing(offer)}>수정</button></article>)}{offers.data&&!offers.data.offers.length&&<p>아직 연결한 상품이나 혜택이 없어요.</p>}</div></>}</>;
}
export function CreatorBusiness() {
  const [params,setParams]=useSearchParams(),code=params.get('code')||'',[page,setPage]=useState(1),signedIn=hasSession();
  const list=useData(signal=>getMyExhibitions(page,signal),[page],signedIn);
  return <Shell title="공간의 반응을 확인하세요" description="전시 방문과 관심을 살펴보고, 상품·예약·쿠폰으로 브랜드의 다음 경험을 연결하세요.">{!signedIn?<div className="exhibition-message"><p>로그인 후 본인 전시를 관리할 수 있어요.</p><Link to="/signin?next=/mypage/business">로그인하기 →</Link></div>:<><Feedback {...list}/><div className="business-gallery-pick"><label>내 전시<select value={list.data?.galleries.some(item=>item.code===code)?code:''} onChange={e=>setParams(e.target.value?{code:e.target.value}:{})}><option value="">관리할 전시를 선택하세요</option>{list.data?.galleries.map(item=><option key={item.code} value={item.code}>{item.title}</option>)}</select></label><Pager page={page} total={list.data?.totalPages||0} setPage={setPage}/></div>{code?<CreatorSelected key={code} code={code}/>:list.data&&!list.data.galleries.length?<p>아직 발행한 전시가 없어요. 제작 프로그램에서 전시를 먼저 발행해 주세요.</p>:<div className="exhibition-message">위 목록에서 전시를 선택하면 통계와 연결 정보를 확인할 수 있어요.</div>}</>}</Shell>;
}
const emptyPromotion=():api.Promotion=>({id:'',code:'',title:'',description:'',sponsor:'',startsOn:'',endsOn:'',enabled:false,sortOrder:0,revision:1});
const emptyPlan=():api.Plan=>({id:'',name:'',summary:'',priceKrw:null,billingUnit:'custom',priceNote:'',features:[],enabled:false,sortOrder:0,revision:1});
function PromotionEditor({initial,done}:{initial:api.Promotion;done:()=>void}) {
  const [form,setForm]=useState(initial),[error,setError]=useState(''),[busy,setBusy]=useState(false);const field=(name:keyof api.Promotion,value:unknown)=>setForm({...form,[name]:value});
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api.savePromotion(form);done();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <form className="business-form" onSubmit={save}><h3>프로모션 설정</h3><p className="business-muted">광고 표시와 광고주 이름이 함께 노출돼요. 기간 안에 공개·승인된 전시만 홈에 표시됩니다.</p><fieldset disabled={busy}><label>전시 코드<input required maxLength={45} value={form.code} onChange={e=>field('code',e.target.value)}/></label><label>프로모션 제목<input required maxLength={100} value={form.title} onChange={e=>field('title',e.target.value)}/></label><label>소개<textarea maxLength={300} rows={3} value={form.description} onChange={e=>field('description',e.target.value)}/></label><label>광고주·브랜드 이름<input required maxLength={100} value={form.sponsor} onChange={e=>field('sponsor',e.target.value)}/></label><div className="business-form-row"><label>시작일<input required type="date" value={form.startsOn} onChange={e=>field('startsOn',e.target.value)}/></label><label>종료일<input required type="date" min={form.startsOn||undefined} value={form.endsOn} onChange={e=>field('endsOn',e.target.value)}/></label><label>노출 순서<input required type="number" min={0} max={999} value={form.sortOrder} onChange={e=>field('sortOrder',Number(e.target.value))}/></label></div><label className="business-check"><input type="checkbox" checked={form.enabled} onChange={e=>field('enabled',e.target.checked)}/>기간에 맞춰 공개</label><button className="discovery-primary">{busy?'저장 중…':'프로모션 저장'}</button><button type="button" onClick={done}>닫기</button></fieldset>{error&&<p role="alert">{error}</p>}</form>;
}
function PlanEditor({initial,done}:{initial:api.Plan;done:()=>void}) {
  const [form,setForm]=useState(initial),[features,setFeatures]=useState(initial.features.join('\n')),[error,setError]=useState(''),[busy,setBusy]=useState(false);const field=(name:keyof api.Plan,value:unknown)=>setForm({...form,[name]:value});
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api.savePlan({...form,features:features.split('\n').map(x=>x.trim()).filter(Boolean)});done();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <form className="business-form" onSubmit={save}><h3>요금제 설정</h3><p className="business-muted">문의형 요금제예요. 설정한 가격은 안내에 사용되며 결제나 이용 권한을 변경하지 않습니다.</p><fieldset disabled={busy}><label>요금제 이름<input required maxLength={100} value={form.name} onChange={e=>field('name',e.target.value)}/></label><label>소개<textarea rows={3} maxLength={300} value={form.summary} onChange={e=>field('summary',e.target.value)}/></label><div className="business-form-row"><label>안내 금액 · 원<input type="number" min={0} max={1000000000} step={1} placeholder="비우면 별도 협의" value={form.priceKrw??''} onChange={e=>field('priceKrw',e.target.value===''?null:Number(e.target.value))}/></label><label>금액 단위<select value={form.billingUnit} onChange={e=>field('billingUnit',e.target.value)}><option value="custom">별도 기준</option><option value="month">월</option><option value="exhibition">전시당</option></select></label></div><label>금액 부가 설명<input maxLength={100} placeholder="부가세 포함 여부, 별도 협의 조건 등" value={form.priceNote} onChange={e=>field('priceNote',e.target.value)}/></label><label>포함 구성 · 한 줄에 하나<textarea rows={6} maxLength={1931} value={features} onChange={e=>setFeatures(e.target.value)}/><small>최대 12개 · 항목당 160자</small></label><label>노출 순서<input required type="number" min={0} max={999} value={form.sortOrder} onChange={e=>field('sortOrder',Number(e.target.value))}/></label><label className="business-check"><input type="checkbox" checked={form.enabled} onChange={e=>field('enabled',e.target.checked)}/>요금제 공개</label><button className="discovery-primary">{busy?'저장 중…':'요금제 저장'}</button><button type="button" onClick={done}>닫기</button></fieldset>{error&&<p role="alert">{error}</p>}</form>;
}
function ReviewOffer({offer,reload}:{offer:api.Offer;reload:()=>void}) {
  const [note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function review(status:string){setBusy(true);setError('');try{await api.decideOffer(offer,status,note);reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <article className="business-review"><span className={`community-status ${offer.reviewStatus}`}>{reviewLabel(offer.reviewStatus)}</span><h3>{offer.title}</h3><p>{offerKind(offer.kind)} · {offer.enabled?'공개 요청 중':'숨김'} · 전시 {offer.code}</p><p>{offer.description}</p><a className="business-url" href={offer.url} target="_blank" rel="noopener noreferrer">{offer.url} ↗</a>{offer.couponCode&&<p>공통 쿠폰 코드: {offer.couponCode}</p>}<p>{offer.startsOn||'시작 제한 없음'} — {offer.endsOn||'종료 제한 없음'}</p>{offer.reviewNote&&<p>이전 사유: {offer.reviewNote}</p>}<label>연결 심사 사유<textarea aria-label={`${offer.title} 연결 심사 사유`} rows={2} maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="community-action-row"><button disabled={busy} onClick={()=>review('approved')}>연결 승인</button><button disabled={busy||note.trim().length<5} onClick={()=>review('rejected')}>연결 반려</button></div>{error&&<p role="alert">{error}</p>}</article>;
}
export function BusinessAdmin() {
  const access=useData(getCurationAccess,[]),allowed=!!access.data?.isPlatformAdmin;
  const [tab,setTab]=useState('promotions'),[promotion,setPromotion]=useState<api.Promotion|null>(null),[plan,setPlan]=useState<api.Plan|null>(null),[status,setStatus]=useState('pending'),[page,setPage]=useState(1);
  const promotions=useData(signal=>api.getPromotions(true,signal),[],allowed&&tab==='promotions');
  const plans=useData(signal=>api.getPlans(true,signal),[],allowed&&tab==='plans');
  const offers=useData(signal=>api.getOfferReviews(status,page,signal),[status,page],allowed&&tab==='offers');
  function switchTab(value:string){setTab(value);setPlan(null);setPromotion(null);}
  return <Shell title="브랜드 운영 관리" description="프로모션 일정과 요금제를 관리하고 전시의 외부 연결을 검토하세요."><p><Link to="/admin/exhibitions">홈 노출 관리</Link>{exhibitionReviewEnabled && <> · <Link to="/admin/moderation">공개 심사·신고 관리</Link></>}</p><Feedback {...access}/>{allowed&&<><nav className="exhibition-filter-chips" aria-label="사업 운영 기능">{[['promotions','프로모션 전시'],['plans','요금제'],['offers','상품·예약·쿠폰 심사']].map(([value,label])=><button key={value} aria-pressed={tab===value} onClick={()=>switchTab(value)}>{label}</button>)}</nav>
    {tab==='promotions'&&<><Feedback {...promotions}/>{promotion?<PromotionEditor key={promotion.id||'new'} initial={promotion} done={()=>{setPromotion(null);promotions.reload();}}/>:<button className="discovery-primary" onClick={()=>setPromotion(emptyPromotion())}>프로모션 추가 +</button>}<p className="business-muted">홈에는 조건에 맞는 최대 6개를 노출 순서대로 표시해요.</p><div className="business-admin-list">{promotions.data?.promotions.map(item=><article key={item.id}><span className="business-ad">광고 · {item.sponsor}</span><h3>{item.title}</h3><p>{item.startsOn} — {item.endsOn} · {item.enabled?'공개 설정':'숨김'}</p><p className="business-muted">전시 {item.code}</p><button disabled={!!promotion} onClick={()=>setPromotion(item)}>수정</button></article>)}{promotions.data&&!promotions.data.promotions.length&&<p>등록한 프로모션이 없어요.</p>}</div></>}
    {tab==='plans'&&<><Feedback {...plans}/>{plan?<PlanEditor key={plan.id||'new'} initial={plan} done={()=>{setPlan(null);plans.reload();}}/>:<button className="discovery-primary" onClick={()=>setPlan(emptyPlan())}>요금제 추가 +</button>}<p><Link to="/pricing">공개 요금제 페이지 보기 ↗</Link></p><div className="business-admin-list">{plans.data?.plans.map(item=><article key={item.id}><span className="community-status">{item.enabled?'공개':'숨김'}</span><h3>{item.name}</h3><p>{priceText(item)}</p><button disabled={!!plan} onClick={()=>setPlan(item)}>수정</button></article>)}{plans.data&&!plans.data.plans.length&&<p>등록한 요금제가 없어요. 실제 제공할 구성과 가격을 입력해 주세요.</p>}</div></>}
    {tab==='offers'&&<><label>심사 상태 <select aria-label="연결 심사 상태" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="pending">심사 대기</option><option value="approved">승인</option><option value="rejected">반려</option></select></label><Feedback {...offers}/><div className="business-review-list">{offers.data?.offers.map(item=><ReviewOffer key={`${item.id}-${item.revision}`} offer={item} reload={offers.reload}/>)}{offers.data&&!offers.data.offers.length&&<p>해당 상태의 연결이 없어요.</p>}</div><Pager page={page} total={offers.data?.totalPages||0} setPage={setPage}/></>}
  </>}</Shell>;
}
